
packages:
  - 'ui'
  - 'widgets/**'
  - 'packages/**'

catalog:
  react: '^18.3.1'
  react-dom: '^18.3.1'
  zebar: '^3.1.0'
  tailwindcss: '^3.4.15'
  postcss: '^8.4.49'
  '@types/react': '^18.3.23'
  '@types/react-dom': '^18.3.7' 